### ISSUE TITLE
could you please give me the preprocessed data of mnist

### ISSUE THREAD

**Issue by wenhuazang** [yunjey/dtn-tensorflow#1]
Mnist images need to be replicated the grayscale image three times and reseize.could you please give me the preprocessed data of mnist, thank you!

**Comment by stevenygd** [comment]
I have a sniper of codes doing the job:
https://github.com/stevenygd/domain-transfer-network-tensorflow/blob/master/make_mnist.py

**Comment by wenhuazang** [comment]
Good job! Thanks a lot. @stevenygd

**Comment by yunjey** [comment]
I've updated the code, you can download mnist dataset by running prepro.py
