### ISSUE TITLE
The result is not good

### ISSUE THREAD

**Issue by wenhuazang** [yunjey/dtn-tensorflow#2]
I run the code, founding that the result is not good, i dont know why.Is it the problem about the code? @yunjey @stevenygd

**Comment by yunjey** [comment]
This project is currently in progress. In other words, code is still incomplete, so it is normal that the results are strange.

**Comment by wenhuazang** [comment]
Ok, i also will complete it. If i have a better result, i will share with you.Thanks for your reply.

**Comment by yunjey** [comment]
I've updated the code, the result was better than before.
