### ISSUE TITLE
Problem running the code

### ISSUE THREAD

**Issue by gvillalonga89** [yunjey/dtn-tensorflow#3]
Hi,

I tried today to run the code as it is said on the readme file but I get this error on the training part (python main.py --mode='train'): 
[log.txt](https://github.com/yunjey/dtn-tensorflow/files/726957/log.txt)

Do you have any idea what can be the issue there?

**Comment by yunjey** [comment]
The file is very inconvenient to view.
Did you run the code in a terminal environment other than ipython notebook?

**Comment by gvillalonga89** [comment]
I run the code on linux terminal.
I add the ipython notebook run. Thank you for your time.
[test_error.ipynb.zip](https://github.com/yunjey/dtn-tensorflow/files/727164/test_error.ipynb.zip)

**Comment by gvillalonga89** [comment]
tensorflow (0.12.1)

**Comment by yunjey** [comment]
I modified the code by adding name scopes. Try the code again.

**Comment by kentkawai** [comment]
I still have the same error with current code.
